test

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -2,17 +2,16 @@ name: List Expired Branches
 author: DevOps
 description: List expired branches json based on retention policy
 
+# Expected Variables
+# ~ $days_retention
+# ~ $repository
+# ~ $namespace
+
 inputs:
   days-retention:
     description: 'Retention policy days'
     required: false
     default: 14
-  repository:
-    description: 'Repository'
-  namespace: 
-    description: 'Namespace'
-  branch:
-    description: 'Branch'
 
 outputs:
   has-branches:
@@ -25,13 +24,22 @@ outputs:
 runs:
   using: 'composite'
   steps:
+  - shell: bash
+    if: (env.days_retention == '' && inputs.days-retention == '') || env.repository == '' || env.repository == ''
+    run: |
+      echo "Failed expected variables check."
+      exit 1
+
+  - shell: bash
+    if: env.days_retention == '' && inputs.days-retention != ''
+    run: |
+      $days_retention = ${{ inputs.days-retention }}
+
   - uses: actions/checkout@v4
     with:
       fetch-depth: 0 # Fetch all history for all branches and tags
       
   - id: branches
-    env:
-      days_retention: ${{ inputs.days-retention }}
     shell: bash
     run: |
       bash ${{ github.action_path }}/gha/expired-branches.sh
